### PR TITLE
[WIP] Build canvas with ALT_CMAKE option

### PR DESCRIPTION
**Pull request by gartung**
Hi Ben,

Use "cmake -DALT_CMAKE=1" to configure. The build fails with Root 6.07.02 so I am trying again with Root 6.06.0X.

Patrick

### CODE REVIEW

**Comment by drbenmorgan** [comment]
Thanks for getting started here @gartung - I'll take a look through, but may not be until next week. Please keep adding functionality though!

**Comment by gartung** [comment]
This finally works with the few extra files I added to my cetbuildtools2 fork. You will probably want to merge the latest develop into your branch before you attempt a merge of this. Fell free to use git merge --swash. Some of my comments at the end were just silly.

**Comment by gartung** [comment]
I still can't figure out why the exported interfaces from cetlib,messagefacility and fhiclcpp did not import correctly. The library directory is named lib64 and I think find_package only looks in lib: https://cmake.org/cmake/help/v3.0/command/find_package.html Maybe the project config files should be moved to share.

**Comment by gartung** [comment]
This is all I see in CMakeCache.txt

//The directory containing a CMake configuration file for cetbuildtools2.
cetbuildtools2_DIR:PATH=/home/gartung/spack/opt/spack/linux-x86_64/gcc-4.9.3/cetbuildtools2-dev-zumay5k6v3eqraglv3gzwb7y24sqx7bk/share/cetbuildtools2/cmake

//The directory containing a CMake configuration file for cetlib.
cetlib_DIR:PATH=/home/gartung/spack/opt/spack/linux-x86_64/gcc-4.9.3/cetlib-dev-ghdb5ww5a7q7owkj2vvqmewrnlhstxtw/lib64/cmake/cetlib

//The directory containing a CMake configuration file for fhiclcpp.
fhiclcpp_DIR:PATH=/home/gartung/spack/opt/spack/linux-x86_64/gcc-4.9.3/fhicl-cpp-dev-r5yv7ocs7hh6k775g2g4kkvqqsud7z2q/lib64/cmake/fhiclcpp

//The directory containing a CMake configuration file for messagefacility.
messagefacility_DIR:PATH=/home/gartung/spack/opt/spack/linux-x86_64/gcc-4.9.3/messagefacility-dev-62r57l2ovpxce3xhv55zvxhpr2xjkyfv/lib64/cmake/messagefacility

**Comment by drbenmorgan** [comment]
@gartung thanks agin for the updates, I've worked through them a bit, and have made some updates on the [gartung-features/modern-cmake](https://github.com/drbenmorgan/fnal-canvas/tree/gartung-feature/modern-cmake) branch. The major updates are:
- Bring CheckClassVersion/BuildDictionary.cmake into canvas. I think, for now, these belong here rather than cetbuildtools2 because they are specific to and depend on canvas/art functionality. Any changes needed to support canvas are most easily done in-place here. This can be reviewed in future though as canvas/art/gallery stabilize.
- Some simplification of the link lists to remove no longer needed library dependencies.
- Tests are all added, built, and can be run

Some caveats:
- The changes to checkClassVersion are not fully tested, though I note f2be82d838fa1a8ff611cc9da91d661838fb2f3a. Also note that the Python script still includes some UPSisms
- Some of the tests fail on Apple/Clang due to typename demangling issues from inline namespaces. I suspect this will also be an issue on GCC 5/6, and the resolution is probably similar to [that reported in fhicl-cpp](https://cdcvs.fnal.gov/redmine/issues/11860).

If you could pull the changes from that branch into your feature/modern-cmake branch, test and recommit with any further fixes, I think we'll be in a position to merge. There are still some fixes to the installed cmake scripts, but these can wait until the gross features are in place.

**Comment by gartung** [comment]
The art people moved the CheckClassVersion cmake macro and checkClassVersion python script to cetbuildtools with the art/canvas split. I think BuildDictionary cmake macro was already there.

**Comment by drbenmorgan** [comment]
> The art people moved the CheckClassVersion cmake macro and checkClassVersion python script to cetbuildtools with the art/canvas split. I think BuildDictionary cmake macro was already there.

O.k., but for now I'd like to keep them in canvas for this work until their exact dependencies and purpose is better defined.

**Comment by gartung** [comment]
Hi Ben,
I merged your changes, but I noticed that you made changes to source code. I want to avoid changing source code at all. I have reverted your changes on this branch.

**Comment by gartung** [comment]
Oh never mind  Those are upstream changes.

**Comment by gartung** [comment]
Changing the branch name to alt-cmake with only changes to cmake files. I will do the same for cetlib, messagefacility and fhicl-cpp

**Comment by drbenmorgan** [comment]
O.k., I'll also try moving the commit related to source changes, but there are other commits in this branch that make these changes. I think we can only keep build/sources changes separated if we make and test all build (i.e. CMake script) changes against a _single_ OS/compiler set. This would be made to work, and then changes made as needed on other systems, but these are likely to involve _both_ source and build script changes.

I'd propose to make this equivalent to the current "e10" qualifier, so Linux/gcc 4.9.3/c++14. Let's leave trying Mac gcc or clang until the base build is sorted.

Thoughts?

**Comment by gartung** [comment]
That works for me. 
Looking at the canvas branch I realized that I have changes to the code for the clang build on OSX. 
Eventually I would like to make the cmake file changes into a patch that can be saved in the artstack-spack repo. Putiing all of the changes in altCMakeLists.cmake simplifies patch updates.

**Comment by drbenmorgan** [comment]
Though it's messy, and I believe not recommended, it should be possible to create the new "alt-cmake" branches from the current develop branches, and cherry-pick commits that only touch CMake files across. Without going through everything, it's possible that some commits might touch both source/cmake files.

Once you have alt-cmake branches set up for everything up to canvas, just PR them, and I can start cherry picking changes from the modern-cmake branches into them if needed.

**Pull request closed without merging**
